[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
